version: '2'
services:
  db:
    image: couchdb:latest    
    ports:
      - "35984:5984"
  web:
    image: markwatsonatx/swift-kitura-sample:0.32   
    volumes:
      - ./src:/usr/src
    environment:
      - KITURA_SAMPLE_HOME=/usr/src
    ports:
      - "38090:8090"
    depends_on:
      - db